var site = 'sites/detail/:siteName',
  user = site + '/users/detail/:userId',
  analysisMonth = 'analysis/months/:month',
  analysisWeek = 'analysis/weeks/:week',
  analysisDate = 'analysis/dates/:date',
  paths = {
    'order-analysis': site+'/orders/analysis/:path',
    'order-analysis-month': site+'/orders/'+analysisMonth,
    'order-analysis-week': site+'/orders/'+analysisWeek,
    'order-analysis-date': site+'/orders/'+analysisDate,
    'servers': 'servers',
    'queue': 'queue',
    'queue-tasks': 'queue/tasks',
    'queue-task': 'queue/tasks/:id',
    'query-request': 'query/request',
    'query-response': 'query/response',
    'query-specs': 'query/specs',
    'query-cache': 'query/cache',
    'templates':'templates/:type',
    'template':'templates/:type/:id',
    'my-sites':'users/detail/:uid/sites',
    'user-path':'users/detail/:userId/:path',
    'sites': 'sites/:type',
    'site': 'sites/:type/:siteName',
    'site-path':site+'/:path',
    'site-config-preload': site+'/config/preload',
    'site-config-payment':site+'/config/payments/:provider',
    'temps':'temp/:type/:provider',
    'files':site+'/files',
    'file-path':site+'/files/:path',
    'file-root-path':site+'/files:path',
    'user': user,
    'users-site': site + '/users/:type/:userId',
    'site-users': site + '/users/:type',
    'site-user': site + '/users/:type/:userId',
    'pages':site+'/pages/:type',
    'page':site+'/pages/:type/:id',
    'page-property':site+'/pages/:type/:id/:property',
    'widgets':site+'/widgets/:type',
    'widget':site+'/widgets/:type/:id',
    'products': site + '/products/:type',
    'product-categories': site + '/products/config/categories',
    'product': site + '/products/:type/:id',
    'articles': site + '/articles/:type',
    'article-categories': site + '/articles/config/categories',
    'article': site + '/articles/:type/:id',
    'orders': site + '/orders/:type',
    'site-orders': site + '/orders/:type',
    'user-order': user + '/orders/:type/:id',
    'orders-analysis': site + '/orders/analysis/:dateId',
    'notifications':'users/detail/:uid/notifications'
  };


module.exports = {
  projectId: 'project-3415547818359859659',
  serviceAccount: "./quartz-8fdc0aa77390.json",
  databaseURL: "https://quartz.firebaseio.com",
  paths: paths
};
